version: '3'

services:

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - $PWD:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - 9090:9090

volumes:
  prometheus:
